/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckSessionTypeModel
 */
export interface CheckSessionTypeModel {
    /**
     * 
     * @type {boolean}
     * @memberof CheckSessionTypeModel
     */
    hasSession?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof CheckSessionTypeModel
     */
    sessionId?: string | null;
}

/**
 * Check if a given object implements the CheckSessionTypeModel interface.
 */
export function instanceOfCheckSessionTypeModel(value: object): value is CheckSessionTypeModel {
    return true;
}

export function CheckSessionTypeModelFromJSON(json: any): CheckSessionTypeModel {
    return CheckSessionTypeModelFromJSONTyped(json, false);
}

export function CheckSessionTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckSessionTypeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'hasSession': json['hasSession'] == null ? undefined : json['hasSession'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
    };
}

export function CheckSessionTypeModelToJSON(json: any): CheckSessionTypeModel {
    return CheckSessionTypeModelToJSONTyped(json, false);
}

export function CheckSessionTypeModelToJSONTyped(value?: CheckSessionTypeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasSession': value['hasSession'],
        'sessionId': value['sessionId'],
    };
}

