/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimInterestResponseModel
 */
export interface ClaimInterestResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ClaimInterestResponseModel
     */
    message?: string | null;
}

/**
 * Check if a given object implements the ClaimInterestResponseModel interface.
 */
export function instanceOfClaimInterestResponseModel(value: object): value is ClaimInterestResponseModel {
    return true;
}

export function ClaimInterestResponseModelFromJSON(json: any): ClaimInterestResponseModel {
    return ClaimInterestResponseModelFromJSONTyped(json, false);
}

export function ClaimInterestResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimInterestResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ClaimInterestResponseModelToJSON(json: any): ClaimInterestResponseModel {
    return ClaimInterestResponseModelToJSONTyped(json, false);
}

export function ClaimInterestResponseModelToJSONTyped(value?: ClaimInterestResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

