/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatesModel
 */
export interface CoordinatesModel {
    /**
     * 
     * @type {number}
     * @memberof CoordinatesModel
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinatesModel
     */
    longitude?: number;
}

/**
 * Check if a given object implements the CoordinatesModel interface.
 */
export function instanceOfCoordinatesModel(value: object): value is CoordinatesModel {
    return true;
}

export function CoordinatesModelFromJSON(json: any): CoordinatesModel {
    return CoordinatesModelFromJSONTyped(json, false);
}

export function CoordinatesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatesModel {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function CoordinatesModelToJSON(json: any): CoordinatesModel {
    return CoordinatesModelToJSONTyped(json, false);
}

export function CoordinatesModelToJSONTyped(value?: CoordinatesModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

