/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoJsonProperties
 */
export interface GeoJsonProperties {
    /**
     * 
     * @type {string}
     * @memberof GeoJsonProperties
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoJsonProperties
     */
    mooringPinId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoJsonProperties
     */
    icon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GeoJsonProperties
     */
    layer?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GeoJsonProperties
     */
    rotate?: number;
}

/**
 * Check if a given object implements the GeoJsonProperties interface.
 */
export function instanceOfGeoJsonProperties(value: object): value is GeoJsonProperties {
    return true;
}

export function GeoJsonPropertiesFromJSON(json: any): GeoJsonProperties {
    return GeoJsonPropertiesFromJSONTyped(json, false);
}

export function GeoJsonPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJsonProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'mooringPinId': json['mooringPinId'] == null ? undefined : json['mooringPinId'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'layer': json['layer'] == null ? undefined : json['layer'],
        'rotate': json['rotate'] == null ? undefined : json['rotate'],
    };
}

export function GeoJsonPropertiesToJSON(json: any): GeoJsonProperties {
    return GeoJsonPropertiesToJSONTyped(json, false);
}

export function GeoJsonPropertiesToJSONTyped(value?: GeoJsonProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'mooringPinId': value['mooringPinId'],
        'icon': value['icon'],
        'layer': value['layer'],
        'rotate': value['rotate'],
    };
}

