/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IconModel
 */
export interface IconModel {
    /**
     * 
     * @type {string}
     * @memberof IconModel
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IconModel
     */
    value?: string | null;
}

/**
 * Check if a given object implements the IconModel interface.
 */
export function instanceOfIconModel(value: object): value is IconModel {
    return true;
}

export function IconModelFromJSON(json: any): IconModel {
    return IconModelFromJSONTyped(json, false);
}

export function IconModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): IconModel {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function IconModelToJSON(json: any): IconModel {
    return IconModelToJSONTyped(json, false);
}

export function IconModelToJSONTyped(value?: IconModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

