/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceModel } from './ServiceModel';
import {
    ServiceModelFromJSON,
    ServiceModelFromJSONTyped,
    ServiceModelToJSON,
    ServiceModelToJSONTyped,
} from './ServiceModel';
import type { MarinaTypeModel } from './MarinaTypeModel';
import {
    MarinaTypeModelFromJSON,
    MarinaTypeModelFromJSONTyped,
    MarinaTypeModelToJSON,
    MarinaTypeModelToJSONTyped,
} from './MarinaTypeModel';

/**
 * 
 * @export
 * @interface MarinaModel
 */
export interface MarinaModel {
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof MarinaModel
     */
    geoJsonId?: number;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    coordinates?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    canalplanLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    canalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaModel
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MarinaModel
     */
    distanceFromSearch?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MarinaModel
     */
    distanceFromUser?: number | null;
    /**
     * 
     * @type {MarinaTypeModel}
     * @memberof MarinaModel
     */
    marinaType?: MarinaTypeModel;
    /**
     * 
     * @type {Array<ServiceModel>}
     * @memberof MarinaModel
     */
    services?: Array<ServiceModel> | null;
}

/**
 * Check if a given object implements the MarinaModel interface.
 */
export function instanceOfMarinaModel(value: object): value is MarinaModel {
    return true;
}

export function MarinaModelFromJSON(json: any): MarinaModel {
    return MarinaModelFromJSONTyped(json, false);
}

export function MarinaModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarinaModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'geoJsonId': json['geoJsonId'] == null ? undefined : json['geoJsonId'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
        'canalplanLink': json['canalplanLink'] == null ? undefined : json['canalplanLink'],
        'website': json['website'] == null ? undefined : json['website'],
        'address': json['address'] == null ? undefined : json['address'],
        'canalName': json['canalName'] == null ? undefined : json['canalName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'distanceFromSearch': json['distanceFromSearch'] == null ? undefined : json['distanceFromSearch'],
        'distanceFromUser': json['distanceFromUser'] == null ? undefined : json['distanceFromUser'],
        'marinaType': json['marinaType'] == null ? undefined : MarinaTypeModelFromJSON(json['marinaType']),
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(ServiceModelFromJSON)),
    };
}

export function MarinaModelToJSON(json: any): MarinaModel {
    return MarinaModelToJSONTyped(json, false);
}

export function MarinaModelToJSONTyped(value?: MarinaModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'geoJsonId': value['geoJsonId'],
        'name': value['name'],
        'type': value['type'],
        'coordinates': value['coordinates'],
        'canalplanLink': value['canalplanLink'],
        'website': value['website'],
        'address': value['address'],
        'canalName': value['canalName'],
        'phoneNumber': value['phoneNumber'],
        'distanceFromSearch': value['distanceFromSearch'],
        'distanceFromUser': value['distanceFromUser'],
        'marinaType': MarinaTypeModelToJSON(value['marinaType']),
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(ServiceModelToJSON)),
    };
}

