/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarinaTypeModel
 */
export interface MarinaTypeModel {
    /**
     * 
     * @type {string}
     * @memberof MarinaTypeModel
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaTypeModel
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarinaTypeModel
     */
    iconKey?: string | null;
}

/**
 * Check if a given object implements the MarinaTypeModel interface.
 */
export function instanceOfMarinaTypeModel(value: object): value is MarinaTypeModel {
    return true;
}

export function MarinaTypeModelFromJSON(json: any): MarinaTypeModel {
    return MarinaTypeModelFromJSONTyped(json, false);
}

export function MarinaTypeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarinaTypeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'iconKey': json['iconKey'] == null ? undefined : json['iconKey'],
    };
}

export function MarinaTypeModelToJSON(json: any): MarinaTypeModel {
    return MarinaTypeModelToJSONTyped(json, false);
}

export function MarinaTypeModelToJSONTyped(value?: MarinaTypeModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'iconKey': value['iconKey'],
    };
}

