/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewClaimInterestModel
 */
export interface NewClaimInterestModel {
    /**
     * 
     * @type {string}
     * @memberof NewClaimInterestModel
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewClaimInterestModel
     */
    marinaName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewClaimInterestModel
     */
    sessionId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NewClaimInterestModel
     */
    submissionTimeStamp?: Date | null;
}

/**
 * Check if a given object implements the NewClaimInterestModel interface.
 */
export function instanceOfNewClaimInterestModel(value: object): value is NewClaimInterestModel {
    return true;
}

export function NewClaimInterestModelFromJSON(json: any): NewClaimInterestModel {
    return NewClaimInterestModelFromJSONTyped(json, false);
}

export function NewClaimInterestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewClaimInterestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'marinaName': json['marinaName'] == null ? undefined : json['marinaName'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'submissionTimeStamp': json['submissionTimeStamp'] == null ? undefined : (new Date(json['submissionTimeStamp'])),
    };
}

export function NewClaimInterestModelToJSON(json: any): NewClaimInterestModel {
    return NewClaimInterestModelToJSONTyped(json, false);
}

export function NewClaimInterestModelToJSONTyped(value?: NewClaimInterestModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'marinaName': value['marinaName'],
        'sessionId': value['sessionId'],
        'submissionTimeStamp': value['submissionTimeStamp'] == null ? undefined : ((value['submissionTimeStamp'] as any).toISOString()),
    };
}

