/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionnaireResponseModel
 */
export interface QuestionnaireResponseModel {
    /**
     * 
     * @type {string}
     * @memberof QuestionnaireResponseModel
     */
    message?: string | null;
}

/**
 * Check if a given object implements the QuestionnaireResponseModel interface.
 */
export function instanceOfQuestionnaireResponseModel(value: object): value is QuestionnaireResponseModel {
    return true;
}

export function QuestionnaireResponseModelFromJSON(json: any): QuestionnaireResponseModel {
    return QuestionnaireResponseModelFromJSONTyped(json, false);
}

export function QuestionnaireResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function QuestionnaireResponseModelToJSON(json: any): QuestionnaireResponseModel {
    return QuestionnaireResponseModelToJSONTyped(json, false);
}

export function QuestionnaireResponseModelToJSONTyped(value?: QuestionnaireResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

