/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterSessionModel
 */
export interface RegisterSessionModel {
    /**
     * 
     * @type {string}
     * @memberof RegisterSessionModel
     */
    coordinates?: string | null;
}

/**
 * Check if a given object implements the RegisterSessionModel interface.
 */
export function instanceOfRegisterSessionModel(value: object): value is RegisterSessionModel {
    return true;
}

export function RegisterSessionModelFromJSON(json: any): RegisterSessionModel {
    return RegisterSessionModelFromJSONTyped(json, false);
}

export function RegisterSessionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterSessionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
    };
}

export function RegisterSessionModelToJSON(json: any): RegisterSessionModel {
    return RegisterSessionModelToJSONTyped(json, false);
}

export function RegisterSessionModelToJSONTyped(value?: RegisterSessionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinates': value['coordinates'],
    };
}

