/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestionResponseModel
 */
export interface SuggestionResponseModel {
    /**
     * 
     * @type {string}
     * @memberof SuggestionResponseModel
     */
    message?: string | null;
}

/**
 * Check if a given object implements the SuggestionResponseModel interface.
 */
export function instanceOfSuggestionResponseModel(value: object): value is SuggestionResponseModel {
    return true;
}

export function SuggestionResponseModelFromJSON(json: any): SuggestionResponseModel {
    return SuggestionResponseModelFromJSONTyped(json, false);
}

export function SuggestionResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestionResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function SuggestionResponseModelToJSON(json: any): SuggestionResponseModel {
    return SuggestionResponseModelToJSONTyped(json, false);
}

export function SuggestionResponseModelToJSONTyped(value?: SuggestionResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

