/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClaimInterestResponseModel,
  NewClaimInterestModel,
} from '../models/index';
import {
    ClaimInterestResponseModelFromJSON,
    ClaimInterestResponseModelToJSON,
    NewClaimInterestModelFromJSON,
    NewClaimInterestModelToJSON,
} from '../models/index';

export interface ClaimInterestMarinaClaimInterestAddPostRequest {
    newClaimInterestModel?: NewClaimInterestModel;
}

/**
 * 
 */
export class ClaimInterestApi extends runtime.BaseAPI {

    /**
     */
    async claimInterestMarinaClaimInterestAddPostRaw(requestParameters: ClaimInterestMarinaClaimInterestAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClaimInterestResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/ClaimInterest/marina/claim-interest/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewClaimInterestModelToJSON(requestParameters['newClaimInterestModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClaimInterestResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async claimInterestMarinaClaimInterestAddPost(requestParameters: ClaimInterestMarinaClaimInterestAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClaimInterestResponseModel> {
        const response = await this.claimInterestMarinaClaimInterestAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
