/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LocationModel,
} from '../models/index';
import {
    LocationModelFromJSON,
    LocationModelToJSON,
} from '../models/index';

export interface LocationSearchGetRequest {
    query?: string;
}

/**
 * 
 */
export class LocationApi extends runtime.BaseAPI {

    /**
     */
    async locationSearchGetRaw(requestParameters: LocationSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LocationModel>>> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/location/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LocationModelFromJSON));
    }

    /**
     */
    async locationSearchGet(requestParameters: LocationSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LocationModel>> {
        const response = await this.locationSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
