/* tslint:disable */
/* eslint-disable */
/**
 * AquaTrail_Data
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QuestionnaireModel,
  QuestionnaireResponseModel,
} from '../models/index';
import {
    QuestionnaireModelFromJSON,
    QuestionnaireModelToJSON,
    QuestionnaireResponseModelFromJSON,
    QuestionnaireResponseModelToJSON,
} from '../models/index';

export interface ApiQuestionnairePostRequest {
    questionnaireModel?: Omit<QuestionnaireModel, 'id'|'submissionId'|'sessionId'|'requestTimestamp'>;
}

/**
 * 
 */
export class QuestionnaireApi extends runtime.BaseAPI {

    /**
     */
    async apiQuestionnairePostRaw(requestParameters: ApiQuestionnairePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuestionnaireResponseModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Questionnaire`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuestionnaireModelToJSON(requestParameters['questionnaireModel']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionnaireResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiQuestionnairePost(requestParameters: ApiQuestionnairePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuestionnaireResponseModel> {
        const response = await this.apiQuestionnairePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
